parent: $folder_ids:shared-services
name: logging
iam_by_principals:
  $iam_principals:service_accounts/seed/iac-org-ro:
    - roles/viewer
  $iam_principals:service_accounts/seed/iac-org-rw:
    - roles/owner
services:
  - logging.googleapis.com
  - pubsub.googleapis.com
  - bigquery.googleapis.com
  - cloudfunctions.googleapis.com
  - storage.googleapis.com
log_buckets:
  audit-logs: {}
  iam: {}
  environment-logs: {}
  vpc-sc:
    log_analytics:
      enable: true
    retention: 31
pubsub_topics:
  audit-logs-topic:
    labels:
      env: prod
  splunk-export-topic:
    labels:
      env: prod
  env-logs-topic:
    labels:
      env: prod
datasets:
  audit_logs_dataset:
    friendly_name: "Centralized Audit Logs Dataset"
    location: us-east4
