# yaml-language-server: $schema=../../../../schemas/folder.schema.json
name: Apps
iam_by_principals:
  $iam_principals:service_accounts/iac-0/iac-org-rw:
    - roles/owner
    - roles/logging.admin
    - roles/resourcemanager.folderAdmin
    - roles/resourcemanager.projectCreator
  $iam_principals:service_accounts/iac-0/iac-org-ro:
    - roles/resourcemanager.folderViewer
    - roles/viewer
